---
openapi: "3.0.0"
info:
  title: "OMS Domain API for Inventory"
  description: "The Order Management Inventory Service provides a set of APIs to manage\
    \ Inventory within Order Management System."
  version: "1.0.0"
servers:
- url: ""
paths:
  /inventory:
    get:
      description: "Get Inventory"
      operationId: "Inventory Get Domain API"
      parameters:
      - name: "businessUnit"
        required: false
        in: "query"
        schema:
          type: "string"
      responses:
        "200":
          description: "Delivery Order(DO) Retrieved Successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/inventoryUpdateRequest"
        "400":
          description: "Your request is not valid"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
        "401":
          description: "Security/policy related error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PolicyErrorMessage"
        "404":
          description: "Not found"
          content: {}
        "500":
          description: "Some other/general error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
    post:
      description: "Create Inventory"
      operationId: "Inventory Create Domain API"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/inventoryCreateRequest"
      responses:
        "201":
          description: "Delivery Order(DO) Created Successfully"
        "400":
          description: "Your request is not valid"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
        "401":
          description: "Security/policy related error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PolicyErrorMessage"
        "404":
          description: "Not found"
          content: {}
        "500":
          description: "Some other/general error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
    patch:
      description: "Update Inventory"
      operationId: "Inventory Update Domain API"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/inventoryUpdateRequest"
      responses:
        "200":
          description: "Delivery Order(DO) Updated Successfully"
        "400":
          description: "Your request is not valid"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
        "401":
          description: "Security/policy related error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PolicyErrorMessage"
        "404":
          description: "Not found"
          content: {}
        "500":
          description: "Some other/general error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
components:
  securitySchemes:
    basicAuth:
      type: "http"
      scheme: "basic"
  schemas:
    inventoryCreateRequest:
      example:
        Inventory:
          Header:
            Source: ""
            ActionType: ""
            ReferenceID: ""
            MessageType: ""
            CompanyID: ""
            MsgLocale: ""
            MsgTimeZone: ""
          Message:
            InventoryEvent:
            - BusinessUnit: ""
              TransactionNumber: ""
              TransactionType: ""
              TransactionDateTime: ""
              TransactionAuditData:
                UserName: ""
                ReasonCodeDescription: ""
              InventoryDefinition:
                ItemName: ""
                FacilityName: ""
                InventoryAttributes:
                  InventoryType: ""
                InventoryData:
                  Disposition: ""
                  LockCode: ""
                  Quantity: ""
                  QuantityUOM: ""
                  QuantityAdjType: ""
              TransactionRefData:
                RefField1: ""
                RefField2: ""
                RefField3: ""
      type: "object"
      required:
      - "Inventory"
      properties:
        Inventory:
          type: "object"
          required:
          - "Header"
          - "Message"
          properties:
            Header:
              type: "object"
              required:
              - "Source"
              - "ActionType"
              - "ReferenceID"
              - "MessageType"
              - "CompanyID"
              - "MsgLocale"
              - "MsgTimeZone"
              properties:
                Source:
                  type: "string"
                ActionType:
                  type: "string"
                ReferenceID:
                  type: "string"
                MessageType:
                  type: "string"
                CompanyID:
                  type: "string"
                MsgLocale:
                  type: "string"
                MsgTimeZone:
                  type: "string"
            Message:
              type: "object"
              required:
              - "InventoryEvent"
              properties:
                InventoryEvent:
                  type: "array"
                  items:
                    type: "object"
                    required:
                    - "BusinessUnit"
                    - "TransactionNumber"
                    - "TransactionType"
                    - "TransactionDateTime"
                    - "TransactionAuditData"
                    - "InventoryDefinition"
                    - "TransactionRefData"
                    properties:
                      BusinessUnit:
                        type: "string"
                      TransactionNumber:
                        type: "string"
                      TransactionType:
                        type: "string"
                      TransactionDateTime:
                        type: "string"
                      TransactionAuditData:
                        type: "object"
                        required:
                        - "UserName"
                        - "ReasonCodeDescription"
                        properties:
                          UserName:
                            type: "string"
                          ReasonCodeDescription:
                            type: "string"
                      InventoryDefinition:
                        type: "object"
                        required:
                        - "ItemName"
                        - "FacilityName"
                        - "InventoryAttributes"
                        - "InventoryData"
                        properties:
                          ItemName:
                            type: "string"
                          FacilityName:
                            type: "string"
                          InventoryAttributes:
                            type: "object"
                            required:
                            - "InventoryType"
                            properties:
                              InventoryType:
                                type: "string"
                          InventoryData:
                            type: "object"
                            required:
                            - "Disposition"
                            - "LockCode"
                            - "Quantity"
                            - "QuantityUOM"
                            - "QuantityAdjType"
                            properties:
                              Disposition:
                                type: "string"
                              LockCode:
                                type: "string"
                              Quantity:
                                type: "string"
                              QuantityUOM:
                                type: "string"
                              QuantityAdjType:
                                type: "string"
                      TransactionRefData:
                        type: "object"
                        required:
                        - "RefField1"
                        - "RefField2"
                        - "RefField3"
                        properties:
                          RefField1:
                            type: "string"
                          RefField2:
                            type: "string"
                          RefField3:
                            type: "string"
    inventoryUpdateRequest:
      example:
        Inventory:
          Header:
            Source: ""
            ActionType: ""
            ReferenceID: ""
            MessageType: ""
            CompanyID: ""
            MsgLocale: ""
            MsgTimeZone: ""
          Message:
            InventoryEvent:
            - BusinessUnit: ""
              TransactionNumber: ""
              TransactionType: ""
              TransactionDateTime: ""
              TransactionAuditData:
                UserName: ""
                ReasonCodeDescription: ""
              InventoryDefinition:
                ItemName: ""
                FacilityName: ""
                InventoryAttributes:
                  InventoryType: ""
                InventoryData:
                  Disposition: ""
                  LockCode: ""
                  Quantity: ""
                  QuantityUOM: ""
                  QuantityAdjType: ""
              TransactionRefData:
                RefField1: ""
                RefField2: ""
                RefField3: ""
      type: "object"
      required:
      - "Inventory"
      properties:
        Inventory:
          type: "object"
          required:
          - "Header"
          - "Message"
          properties:
            Header:
              type: "object"
              required:
              - "Source"
              - "ActionType"
              - "ReferenceID"
              - "MessageType"
              - "CompanyID"
              - "MsgLocale"
              - "MsgTimeZone"
              properties:
                Source:
                  type: "string"
                ActionType:
                  type: "string"
                ReferenceID:
                  type: "string"
                MessageType:
                  type: "string"
                CompanyID:
                  type: "string"
                MsgLocale:
                  type: "string"
                MsgTimeZone:
                  type: "string"
            Message:
              type: "object"
              required:
              - "InventoryEvent"
              properties:
                InventoryEvent:
                  type: "array"
                  items:
                    type: "object"
                    required:
                    - "BusinessUnit"
                    - "TransactionNumber"
                    - "TransactionType"
                    - "TransactionDateTime"
                    - "TransactionAuditData"
                    - "InventoryDefinition"
                    - "TransactionRefData"
                    properties:
                      BusinessUnit:
                        type: "string"
                      TransactionNumber:
                        type: "string"
                      TransactionType:
                        type: "string"
                      TransactionDateTime:
                        type: "string"
                      TransactionAuditData:
                        type: "object"
                        required:
                        - "UserName"
                        - "ReasonCodeDescription"
                        properties:
                          UserName:
                            type: "string"
                          ReasonCodeDescription:
                            type: "string"
                      InventoryDefinition:
                        type: "object"
                        required:
                        - "ItemName"
                        - "FacilityName"
                        - "InventoryAttributes"
                        - "InventoryData"
                        properties:
                          ItemName:
                            type: "string"
                          FacilityName:
                            type: "string"
                          InventoryAttributes:
                            type: "object"
                            required:
                            - "InventoryType"
                            properties:
                              InventoryType:
                                type: "string"
                          InventoryData:
                            type: "object"
                            required:
                            - "Disposition"
                            - "LockCode"
                            - "Quantity"
                            - "QuantityUOM"
                            - "QuantityAdjType"
                            properties:
                              Disposition:
                                type: "string"
                              LockCode:
                                type: "string"
                              Quantity:
                                type: "string"
                              QuantityUOM:
                                type: "string"
                              QuantityAdjType:
                                type: "string"
                      TransactionRefData:
                        type: "object"
                        required:
                        - "RefField1"
                        - "RefField2"
                        - "RefField3"
                        properties:
                          RefField1:
                            type: "string"
                          RefField2:
                            type: "string"
                          RefField3:
                            type: "string"
    ErrorMessage:
      required:
      - "code"
      - "dateTime"
      - "description"
      - "message"
      type: "object"
      properties:
        code:
          type: "string"
        dateTime:
          type: "string"
          format: "date-time"
        message:
          type: "string"
        description:
          type: "string"
      additionalProperties: true
      example:
        code: "500"
        dateTime: "2020-06-15T15:52:43.386-06:00"
        message: "ITEM_INVALID_UOM"
        description: "UOM [ISOCode:ME, Abbreviation:mg] not allowed for InfoodsCode:\
          \ VITC"
    PolicyErrorMessage:
      required:
      - "error"
      type: "object"
      properties:
        error:
          type: "string"
      additionalProperties: true
      example:
        error: "Invalid token."
security:
- basicAuth: []
